test: add test that ensures "vmdk" images are build
osbuild/bootc-image-builder pull request #253
Opened 2024-03-08 16:35 UTC by mvo5

The vmdk images cannot be booted easily in qemu so we will just
check that the image is there but do no functional testing.

This is just a stop-gap and maybe even too slow (as we now build multiple images in sequence). The real solution is that any BootcDisk in images always produces a "superdisk" manifest that contains the pipelines for all supported image types. Then we run a single multi-type build with qcow2+raw+ami+vmdk+ova etc. This should be fast (and let's hope the diskspace gods are with us here) and because the images are cached we can always reuse them.

This is a followup for https://github.com/osbuild/bootc-image-builder/pull/251

[draft as this needs https://github.com/osbuild/bootc-image-builder/pull/225]

2024-03-08 16:39 UTC, cgwalters commented
IMO we don't need to test all images on every PR, as it will quickly get unsustainable (or at least, costly and slow).

The best pattern I think is to have a "periodic" (daily, or so) that does integration testing, and allow opt-in on specific PRs.  This is the pattern we use in OpenShift for example, where you can type
`/test e2e-gcp` to opt-in to testing on GCP.

2024-03-08 16:39 UTC, cgwalters reviewed
Looks sane to me overall though!

2024-03-12 10:49 UTC, achilleas-k requested changes
Looks good but I have a few nitpicks below (comments).

2024-03-12 10:49 UTC, achilleas-k commented on test/test_build.py
> +        # qemu boot images can be build with a single innovation
```suggestion
        # qemu boot images can be build with a single invocation
```
?

2024-03-12 10:49 UTC, achilleas-k commented on test/test_build.py
> +        # TODO: ensure that *all* images can be build with the same call, to
```suggestion
        # TODO: ensure that *all* images can be built with the same call, to
```

2024-03-12 10:49 UTC, achilleas-k commented on test/testcases.py
> +NON_QEMU_BOOT_IMAGE_TYPES = ("vmdk",)
Duplicate lines.

2024-03-12 13:05 UTC, achilleas-k approved these changes

2024-03-13 08:31 UTC, mvo5 commented
> IMO we don't need to test all images on every PR, as it will quickly get unsustainable (or at least, costly and slow).
> 
> The best pattern I think is to have a "periodic" (daily, or so) that does integration testing, and allow opt-in on specific PRs. This is the pattern we use in OpenShift for example, where you can type `/test e2e-gcp` to opt-in to testing on GCP.

Yeah, it's a good point, it will become unsustainable at some point, we are hoping to use some tricks to delay the point a little bit though.

2024-03-14 17:40 UTC, achilleas-k approved these changes
:shipit:

2024-03-14 18:33 UTC, merged